name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore the application
      run: dotnet restore CybersecurityBotWPF.csproj

    - name: Build Debug
      run: dotnet build CybersecurityBotWPF.csproj --configuration Debug --no-restore

    - name: Build Release
      run: dotnet build CybersecurityBotWPF.csproj --configuration Release --no-restore

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release Build
        path: bin\Release\net8.0-windows\
